apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: military-voting

resources:
  - namespace.yaml
  - redis-deployment.yaml
  - postgres-deployment.yaml
  - vote-deployment.yaml
  - result-deployment.yaml
  - worker-deployment.yaml
  - secrets.yaml
  - configmap.yaml
