apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
  namespace: military-voting
spec:
  selector:
    matchLabels:
      app: result
  replicas: 2
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: ${REGISTRY}/military-voting-result:latest
        ports:
        - containerPort: 4000
        env:
        - name: DB_HOST
          value: db
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: votingdb
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-password
        - name: NODE_ENV
          value: production
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: military-voting
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: result
