apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: military-voting
type: Opaque
data:
  postgres-password: cG9zdGdyZXM=  # base64 encoded "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: military-voting
type: Opaque
data:
  vote-secret-key: bWlsaXRhcnlfdW5pdF92b3Rpbmdfc3lzdGVtX3NlY3JldA==  # base64 encoded "military_unit_voting_system_secret"
