apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: military-voting
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 2
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: ${REGISTRY}/military-voting-vote:latest
        ports:
        - containerPort: 80
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: vote-secret-key
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: military-voting
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vote
