apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: military-voting
spec:
  replicas: 1  # Single replica for Free Tier
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: vote
        image: ${REGISTRY}/military-voting-freetier/vote-service:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"    # Minimal memory request
            cpu: "50m"        # 0.05 CPU cores
          limits:
            memory: "128Mi"   # Conservative memory limit
            cpu: "100m"       # 0.1 CPU cores
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: vote-secret-key
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: vote
  namespace: military-voting
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: vote
